In [1]:
import numpy as np

from battle_star import generate_puzzle, solve_puzzle, draw_puzzle

Let us generate a puzzle

In [2]:
N = 10
nstars = 2

region_grid, star_grid = generate_puzzle(N, nstars, annealer="leap", num_reads=100)

In [3]:
draw_puzzle(region_grid, star_grid)
print(region_grid, star_grid, sep='\n')

[[7 7 7 7 0 0 4 4 4 4]
 [7 7 7 7 0 0 4 4 4 4]
 [9 9 7 7 0 0 0 4 4 4]
 [9 9 3 3 0 0 5 5 5 5]
 [9 9 3 3 3 8 8 5 5 5]
 [9 9 3 3 3 8 8 5 5 5]
 [9 9 2 3 3 8 8 8 6 6]
 [2 2 2 1 1 8 8 8 6 6]
 [2 2 2 1 1 1 1 6 6 6]
 [2 2 2 1 1 1 1 6 6 6]]
[[0 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 1]
 [1 0 0 0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 1]]


Let us solve the problem for this region

In [4]:
region_grid = np.array([
    [0, 0, 0, 0, 1, 1, 2, 2, 2, 2],
    [0, 4, 0, 0, 1, 1, 1, 2, 1, 1],
    [0, 4, 4, 1, 1, 1, 1, 1, 1, 1],
    [4, 4, 4, 4, 1, 5, 5, 5, 5, 1],
    [4, 4, 1, 1, 1, 1, 1, 1, 5, 1],
    [6, 6, 6, 6, 7, 7, 8, 8, 8, 8],
    [6, 9, 6, 6, 7, 7, 7, 8, 7, 7],
    [6, 9, 9, 7, 7, 7, 7, 7, 7, 7],
    [9, 9, 9, 9, 7, 10, 10, 10, 10, 7],
    [9, 9, 7, 7, 7, 7, 7, 7, 10, 7],
])

In [4]:
solution_grid = solve_puzzle(N, nstars, region_grid, annealer="neal", num_reads=200)
print(solution_grid)

[[1 0 0 0 0 0 0 0 1 0]
 [0 0 0 1 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 1 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 1 0 0 0 0 0 1]
 [0 1 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0 0 0 1]
 [0 0 1 0 0 0 1 0 0 0]]


In [5]:
draw_puzzle(region_grid, solution_grid)