In [1]:
import numpy as np

from generate_puzzle import generate_puzzle
from solve_puzzle import solve_puzzle

Let us generate a puzzle

In [1]:
N = 10
nstars = 2

region_grid, star_grid = generate_puzzle(N, nstars, annealer="neal", num_reads=100)
print(region_grid, star_grid, sep='\n')

NameError: name 'generate_puzzle' is not defined

Let us solve the problem for this region

In [3]:
"""
region_grid = np.array([
    [0, 0, 0, 0, 1, 1, 2, 2, 2, 2],
    [0, 4, 0, 0, 1, 1, 1, 2, 1, 1],
    [0, 4, 4, 1, 1, 1, 1, 1, 1, 1],
    [4, 4, 4, 4, 1, 5, 5, 5, 5, 1],
    [4, 4, 1, 1, 1, 1, 1, 1, 5, 1],
    [6, 6, 6, 6, 7, 7, 8, 8, 8, 8],
    [6, 9, 6, 6, 7, 7, 7, 8, 7, 7],
    [6, 9, 9, 7, 7, 7, 7, 7, 7, 7],
    [9, 9, 9, 9, 7, 10, 10, 10, 10, 7],
    [9, 9, 7, 7, 7, 7, 7, 7, 10, 7],
])
"""

'\nregion_grid = np.array([\n    [0, 0, 0, 0, 1, 1, 2, 2, 2, 2],\n    [0, 4, 0, 0, 1, 1, 1, 2, 1, 1],\n    [0, 4, 4, 1, 1, 1, 1, 1, 1, 1],\n    [4, 4, 4, 4, 1, 5, 5, 5, 5, 1],\n    [4, 4, 1, 1, 1, 1, 1, 1, 5, 1],\n    [6, 6, 6, 6, 7, 7, 8, 8, 8, 8],\n    [6, 9, 6, 6, 7, 7, 7, 8, 7, 7],\n    [6, 9, 9, 7, 7, 7, 7, 7, 7, 7],\n    [9, 9, 9, 9, 7, 10, 10, 10, 10, 7],\n    [9, 9, 7, 7, 7, 7, 7, 7, 10, 7],\n])\n'

In [5]:
solution_grid = solve_puzzle(N, nstars, region_grid, annealer="neal", num_reads=200)
print(solution_grid)

[[0 0 0 0 1 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 1]
 [1 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 1 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]]
